// Placeholder Firebase options. Replace with values generated by `flutterfire configure`.
// Keeping the structure so the app compiles until real options are provided.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not configured. Run flutterfire configure for web.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. Please add configuration.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqU5Td_x0uFcRIsd0XOTBQndyPe0Fblbg',
    appId: '1:755831270984:android:05c5668070f79eb86c727d',
    messagingSenderId: '755831270984',
    projectId: 'agendio-bf0af',
    storageBucket: 'agendio-bf0af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmiuhJavix-0RbRO-WHRyzifMgl6USShg',
    appId: '1:755831270984:ios:10f9da4692205e336c727d',
    messagingSenderId: '755831270984',
    projectId: 'agendio-bf0af',
    storageBucket: 'agendio-bf0af.firebasestorage.app',
    iosBundleId: 'com.example.agendai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    iosBundleId: 'REPLACE_ME',
  );
}